/**
 * Official 70 Barangays of the City of Maasin, Southern Leyte
 * PSGC Locality Code: 086407000
 */
export const MAASIN_BARANGAYS = [
  "Abgao",
  "Asuncion",
  "Bactul I",
  "Bactul II",
  "Badiang",
  "Bagtican",
  "Basak",
  "Bato I",
  "Bato II",
  "Batuan",
  "Baugo",
  "Bilibol",
  "Bogo",
  "Cabadiangan",
  "Cabulihan",
  "Cagnituan",
  "Cambooc",
  "Cansirong",
  "Canturing",
  "Canyuom",
  "Combado",
  "Dongon",
  "Gawisan",
  "Guadalupe",
  "Hanginan",
  "Hantag",
  "Hinapu Daku",
  "Hinapu Gamay",
  "Ibarra",
  "Isagani",
  "Laboon",
  "Lanao",
  "Lib-og",
  "Libhu",
  "Libertad",
  "Lonoy",
  "Lunas",
  "Mahayahay",
  "Malapoc Norte",
  "Malapoc Sur",
  "Mambajao",
  "Manhilo",
  "Mantahan",
  "Maria Clara",
  "Matin-ao",
  "Nasaug",
  "Nati",
  "Nonok Norte",
  "Nonok Sur",
  "Panan-awan",
  "Pansaan",
  "Pasay",
  "Pinaskuhan",
  "Rizal",
  "San Agustin",
  "San Isidro",
  "San Jose",
  "San Rafael",
  "Santa Cruz",
  "Santa Rosa",
  "Santo Niño",
  "Santo Rosario",
  "Sisi",
  "Tagnipa",
  "Tam-is",
  "Tawid",
  "Tigbawan",
  "Tomoy-tomoy",
  "Tunga-tunga",
  "Zaragosa"
];

export default MAASIN_BARANGAYS;
